//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleID { get; set; }
        public string Heading { get; set; }
        public string SubHeading { get; set; }
        public int Category { get; set; }
        public string Username { get; set; }
        public string Image { get; set; }
        public string Content { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual User User { get; set; }
    }
}
